<?php

namespace Database\Seeders;

use App\Models\Alumni;
use App\Models\User;
use Illuminate\Database\Seeder;

class AlumniSeeder extends Seeder
{
    public function run(): void
    {
        $userId = User::query()->value('id'); // ambil 1 user pertama kalau ada

        $items = [
            [
                'name' => 'Ahmad Fauzan',
                'nisn' => '2021000001',
                'gender' => 'male',
                'graduation_year' => 2021,
                'ethnicity' => 'Bugis',
                'domicile' => 'Makassar',
                'address' => 'Jl. Perintis Kemerdekaan, Makassar',
                'profession' => 'Software Engineer',
                'position' => 'Backend Developer',
                'location' => 'makassar',
                'hobby' => 'Membaca dan futsal',
                'contact_number' => '081234567801',
                'email' => 'ahmad.fauzan@example.com',
            ],
            [
                'name' => 'Nur Aisyah',
                'nisn' => '2021000002',
                'gender' => 'female',
                'graduation_year' => 2021,
                'ethnicity' => 'Makassar',
                'domicile' => 'Gowa',
                'address' => 'Jl. Sultan Alauddin, Gowa',
                'profession' => 'Doctor',
                'position' => 'General Practitioner',
                'location' => 'non-makassar',
                'hobby' => 'Memasak dan membaca',
                'contact_number' => '081234567802',
                'email' => 'nur.aisyah@example.com',
            ],
            [
                'name' => 'Muhammad Rizky',
                'nisn' => '2020000003',
                'gender' => 'male',
                'graduation_year' => 2020,
                'ethnicity' => 'Bugis',
                'domicile' => 'Makassar',
                'address' => 'Jl. Tamalanrea Raya, Makassar',
                'profession' => 'Entrepreneur',
                'position' => 'Founder',
                'location' => 'makassar',
                'hobby' => 'Basket dan bisnis',
                'contact_number' => '081234567803',
                'email' => 'muhammad.rizky@example.com',
            ],
            [
                'name' => 'Siti Rahmawati',
                'nisn' => '2020000004',
                'gender' => 'female',
                'graduation_year' => 2020,
                'ethnicity' => 'Toraja',
                'domicile' => 'Makassar',
                'address' => 'Jl. Hertasning, Makassar',
                'profession' => 'Teacher',
                'position' => 'Mathematics Teacher',
                'location' => 'makassar',
                'hobby' => 'Menulis dan berkebun',
                'contact_number' => '081234567804',
                'email' => 'siti.rahmawati@example.com',
            ],
            [
                'name' => 'Andi Pratama',
                'nisn' => '2019000005',
                'gender' => 'male',
                'graduation_year' => 2019,
                'ethnicity' => 'Bugis',
                'domicile' => 'Maros',
                'address' => 'Jl. Poros Maros, Maros',
                'profession' => 'Civil Engineer',
                'position' => 'Site Engineer',
                'location' => 'non-makassar',
                'hobby' => 'Traveling dan fotografi',
                'contact_number' => '081234567805',
                'email' => 'andi.pratama@example.com',
            ],
            [
                'name' => 'Dewi Lestari',
                'nisn' => '2019000006',
                'gender' => 'female',
                'graduation_year' => 2019,
                'ethnicity' => 'Jawa',
                'domicile' => 'Makassar',
                'address' => 'Jl. Pettarani, Makassar',
                'profession' => 'UI/UX Designer',
                'position' => 'Product Designer',
                'location' => 'makassar',
                'hobby' => 'Menggambar dan desain',
                'contact_number' => '081234567806',
                'email' => 'dewi.lestari@example.com',
            ],
            [
                'name' => 'Fajar Nugroho',
                'nisn' => '2018000007',
                'gender' => 'male',
                'graduation_year' => 2018,
                'ethnicity' => 'Makassar',
                'domicile' => 'Jakarta',
                'address' => 'Jl. Tebet Barat, Jakarta Selatan',
                'profession' => 'Data Analyst',
                'position' => 'Business Intelligence Analyst',
                'location' => 'non-makassar',
                'hobby' => 'Coding dan jogging',
                'contact_number' => '081234567807',
                'email' => 'fajar.nugroho@example.com',
            ],
            [
                'name' => 'Aulia Maharani',
                'nisn' => '2018000008',
                'gender' => 'female',
                'graduation_year' => 2018,
                'ethnicity' => 'Bugis',
                'domicile' => 'Makassar',
                'address' => 'Jl. Urip Sumoharjo, Makassar',
                'profession' => 'Lawyer',
                'position' => 'Associate',
                'location' => 'makassar',
                'hobby' => 'Debat dan membaca',
                'contact_number' => '081234567808',
                'email' => 'aulia.maharani@example.com',
            ],
            [
                'name' => 'Ilham Saputra',
                'nisn' => '2017000009',
                'gender' => 'male',
                'graduation_year' => 2017,
                'ethnicity' => 'Bugis',
                'domicile' => 'Bone',
                'address' => 'Jl. Ahmad Yani, Bone',
                'profession' => 'Government Employee',
                'position' => 'Staff',
                'location' => 'non-makassar',
                'hobby' => 'Badminton dan musik',
                'contact_number' => '081234567809',
                'email' => 'ilham.saputra@example.com',
            ],
            [
                'name' => 'Nabila Putri',
                'nisn' => '2017000010',
                'gender' => 'female',
                'graduation_year' => 2017,
                'ethnicity' => 'Makassar',
                'domicile' => 'Makassar',
                'address' => 'Jl. AP Pettarani, Makassar',
                'profession' => 'Marketing Specialist',
                'position' => 'Digital Marketing Specialist',
                'location' => 'makassar',
                'hobby' => 'Content creation dan traveling',
                'contact_number' => '081234567810',
                'email' => 'nabila.putri@example.com',
            ],
        ];

        foreach ($items as $item) {
            Alumni::updateOrCreate(
                [
                    'nisn' => $item['nisn'],
                ],
                [
                    'name' => $item['name'],
                    'gender' => $item['gender'],
                    'graduation_year' => $item['graduation_year'],
                    'ethnicity' => $item['ethnicity'],
                    'domicile' => $item['domicile'],
                    'address' => $item['address'],
                    'profession' => $item['profession'],
                    'position' => $item['position'],
                    'location' => $item['location'],
                    'hobby' => $item['hobby'],
                    'contact_number' => $item['contact_number'],
                    'email' => $item['email'],
                    'image_path' => null,
                    'updated_by' => $userId,
                ]
            );
        }
    }
}